server:
  port: 8080
  forward-headers-strategy: framework
spring:
  application:
    name: cloud-api-gateway
  cloud:
    gateway:
      routes:
        - id: test
          uri: lb://app-core
          predicates:
            - Path=/api/v1/core/**
    loadbalancer:
      configurations: default  # "zone-aware" по гео зонам

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when_authorized
      cache:
        time-to-live: 10s

logging:
  level:
    org.springframework.cloud.gateway: DEBUG